/*
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package xyz.eeckhout.smartcity.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DisplayedRoutesDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-03T20:36:15.687+01:00")
public class DisplayedRoutesDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("datasetId")
  private String datasetId = null;

  @SerializedName("recordId")
  private String recordId = null;

  @SerializedName("encodedCoordinates")
  private String encodedCoordinates = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("facultativeData")
  private String facultativeData = null;

  public DisplayedRoutesDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public DisplayedRoutesDTO datasetId(String datasetId) {
    this.datasetId = datasetId;
    return this;
  }

   /**
   * Get datasetId
   * @return datasetId
  **/
  @ApiModelProperty(value = "")
  public String getDatasetId() {
    return datasetId;
  }

  public void setDatasetId(String datasetId) {
    this.datasetId = datasetId;
  }

  public DisplayedRoutesDTO recordId(String recordId) {
    this.recordId = recordId;
    return this;
  }

   /**
   * Get recordId
   * @return recordId
  **/
  @ApiModelProperty(value = "")
  public String getRecordId() {
    return recordId;
  }

  public void setRecordId(String recordId) {
    this.recordId = recordId;
  }

  public DisplayedRoutesDTO encodedCoordinates(String encodedCoordinates) {
    this.encodedCoordinates = encodedCoordinates;
    return this;
  }

   /**
   * Get encodedCoordinates
   * @return encodedCoordinates
  **/
  @ApiModelProperty(value = "")
  public String getEncodedCoordinates() {
    return encodedCoordinates;
  }

  public void setEncodedCoordinates(String encodedCoordinates) {
    this.encodedCoordinates = encodedCoordinates;
  }

  public DisplayedRoutesDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DisplayedRoutesDTO facultativeData(String facultativeData) {
    this.facultativeData = facultativeData;
    return this;
  }

   /**
   * Get facultativeData
   * @return facultativeData
  **/
  @ApiModelProperty(value = "")
  public String getFacultativeData() {
    return facultativeData;
  }

  public void setFacultativeData(String facultativeData) {
    this.facultativeData = facultativeData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisplayedRoutesDTO displayedRoutesDTO = (DisplayedRoutesDTO) o;
    return Objects.equals(this.id, displayedRoutesDTO.id) &&
        Objects.equals(this.datasetId, displayedRoutesDTO.datasetId) &&
        Objects.equals(this.recordId, displayedRoutesDTO.recordId) &&
        Objects.equals(this.encodedCoordinates, displayedRoutesDTO.encodedCoordinates) &&
        Objects.equals(this.name, displayedRoutesDTO.name) &&
        Objects.equals(this.facultativeData, displayedRoutesDTO.facultativeData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, datasetId, recordId, encodedCoordinates, name, facultativeData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisplayedRoutesDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("    encodedCoordinates: ").append(toIndentedString(encodedCoordinates)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    facultativeData: ").append(toIndentedString(facultativeData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

