/*
 * My API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package xyz.eeckhout.smartcity.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * ServiceOpinionDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-03T20:36:15.687+01:00")
public class ServiceOpinionDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("dateInsert")
  private DateTime dateInsert = null;

  @SerializedName("isVisible")
  private Boolean isVisible = null;

  @SerializedName("writerId")
  private String writerId = null;

  @SerializedName("serviceId")
  private Integer serviceId = null;

  @SerializedName("rowVersion")
  private byte[] rowVersion = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("answerId")
  private Integer answerId = null;

  public ServiceOpinionDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ServiceOpinionDTO dateInsert(DateTime dateInsert) {
    this.dateInsert = dateInsert;
    return this;
  }

   /**
   * Get dateInsert
   * @return dateInsert
  **/
  @ApiModelProperty(required = true, value = "")
  public DateTime getDateInsert() {
    return dateInsert;
  }

  public void setDateInsert(DateTime dateInsert) {
    this.dateInsert = dateInsert;
  }

  public ServiceOpinionDTO isVisible(Boolean isVisible) {
    this.isVisible = isVisible;
    return this;
  }

   /**
   * Get isVisible
   * @return isVisible
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsVisible() {
    return isVisible;
  }

  public void setIsVisible(Boolean isVisible) {
    this.isVisible = isVisible;
  }

  public ServiceOpinionDTO writerId(String writerId) {
    this.writerId = writerId;
    return this;
  }

   /**
   * Get writerId
   * @return writerId
  **/
  @ApiModelProperty(value = "")
  public String getWriterId() {
    return writerId;
  }

  public void setWriterId(String writerId) {
    this.writerId = writerId;
  }

  public ServiceOpinionDTO serviceId(Integer serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId
  **/
  @ApiModelProperty(value = "")
  public Integer getServiceId() {
    return serviceId;
  }

  public void setServiceId(Integer serviceId) {
    this.serviceId = serviceId;
  }

  public ServiceOpinionDTO rowVersion(byte[] rowVersion) {
    this.rowVersion = rowVersion;
    return this;
  }

   /**
   * Get rowVersion
   * @return rowVersion
  **/
  @ApiModelProperty(value = "")
  public byte[] getRowVersion() {
    return rowVersion;
  }

  public void setRowVersion(byte[] rowVersion) {
    this.rowVersion = rowVersion;
  }

  public ServiceOpinionDTO comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(required = true, value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public ServiceOpinionDTO answerId(Integer answerId) {
    this.answerId = answerId;
    return this;
  }

   /**
   * Get answerId
   * @return answerId
  **/
  @ApiModelProperty(value = "")
  public Integer getAnswerId() {
    return answerId;
  }

  public void setAnswerId(Integer answerId) {
    this.answerId = answerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceOpinionDTO serviceOpinionDTO = (ServiceOpinionDTO) o;
    return Objects.equals(this.id, serviceOpinionDTO.id) &&
        Objects.equals(this.dateInsert, serviceOpinionDTO.dateInsert) &&
        Objects.equals(this.isVisible, serviceOpinionDTO.isVisible) &&
        Objects.equals(this.writerId, serviceOpinionDTO.writerId) &&
        Objects.equals(this.serviceId, serviceOpinionDTO.serviceId) &&
        Objects.equals(this.rowVersion, serviceOpinionDTO.rowVersion) &&
        Objects.equals(this.comment, serviceOpinionDTO.comment) &&
        Objects.equals(this.answerId, serviceOpinionDTO.answerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, dateInsert, isVisible, writerId, serviceId, rowVersion, comment, answerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceOpinionDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dateInsert: ").append(toIndentedString(dateInsert)).append("\n");
    sb.append("    isVisible: ").append(toIndentedString(isVisible)).append("\n");
    sb.append("    writerId: ").append(toIndentedString(writerId)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    rowVersion: ").append(toIndentedString(rowVersion)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    answerId: ").append(toIndentedString(answerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

